require 'lims-quality-app/gel-image/score/all'
require 'lims-quality-app/gel-image/gel_image'
require 'lims-quality-app/gel-image/gel_image_persistor'
require 'lims-quality-app/gel-image/create_gel_image'
require 'lims-quality-app/gel-image/gel_filter'
require 'lims-quality-app/gel-image/gel_sequel_filter'
require 'lims-quality-app/gel-image/update_gel_image_score'
require 'lims-quality-app/gel-image/gel_image_resource'
